# Generated by Django 2.2.4 on 2020-05-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWords', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abstractSubmissionDeadline', models.DateField()),
                ('paperSubmissionDeadline', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('resultsDeadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('noPages', models.IntegerField()),
                ('paperKind', models.CharField(choices=[('PDF', 'pdf'), ('DOCX', 'docx'), ('TXT', 'text')], max_length=3)),
                ('evalDecision', models.CharField(choices=[('AC', 'Accepted'), ('NE', 'Not evaluate'), ('RE', 'Rejected')], max_length=2)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='SCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='PCMember',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConferenceManager.Author')),
            ],
            bases=('ConferenceManager.author',),
        ),
        migrations.CreateModel(
            name='PCMemberPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Paper')),
                ('pcMember', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.PCMember')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezEv', models.CharField(choices=[('SA', 'Strong accept'), ('WA', 'Weak accept'), ('NE', 'Neutral'), ('SR', 'Strong reject'), ('WR', 'Weak reject')], max_length=2)),
                ('evaluationDate', models.DateField()),
                ('pcMemberPaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.PCMemberPaper')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resBid', models.CharField(max_length=200)),
                ('biddingDate', models.DateField()),
                ('pcMemberPaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.PCMemberPaper')),
            ],
        ),
        migrations.CreateModel(
            name='PCCoChair',
            fields=[
                ('pcmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConferenceManager.PCMember')),
            ],
            bases=('ConferenceManager.pcmember',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scMember', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.SCMember')),
                ('pcMember', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.PCMember')),
            ],
        ),
    ]
