# Generated by Django 3.0.4 on 2020-03-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('CoordsX', models.FloatField()),
                ('CoordsY', models.FloatField()),
                ('DeadlineAbstract', models.DateField()),
                ('DeadlineBiding', models.DateField()),
                ('DeadlinePaper', models.DateField()),
                ('DeadlineReview', models.DateField()),
                ('Descriprion', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('OwnerEmail', models.DateField()),
                ('Price', models.FloatField()),
                ('ResearchTopics', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCategory', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('photoURL', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference')),
            ],
        ),
    ]
