# Generated by Django 3.0.4 on 2020-03-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('coordsX', models.FloatField()),
                ('coordsY', models.FloatField()),
                ('deadlineAbstract', models.DateField()),
                ('deadlineBiding', models.DateField()),
                ('deadlinePaper', models.DateField()),
                ('deadlineReview', models.DateField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('ownerEmail', models.DateField()),
                ('price', models.FloatField()),
                ('researchTopics', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCategory', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('photoURL', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('conferenceCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                         to='ConferenceManager.ConferenceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorEmail', models.EmailField(max_length=254)),
                ('conferenceName', models.CharField(max_length=255)),
                ('fileURL', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=255)),
                ('conference',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference')),
            ],
        ),

        migrations.AlterField(
            model_name='conferencecategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
