# Generated by Django 2.2.4 on 2020-05-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scmember',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='section',
            name='pcMember',
        ),
        migrations.AddField(
            model_name='author',
            name='conference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='scMember',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.SCMember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ManyToManyField(to='ConferenceManager.Author'),
        ),
        migrations.AddField(
            model_name='section',
            name='paper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Paper'),
            preserve_default=False,
        ),
    ]
