# Generated by Django 3.0.6 on 2020-05-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='paperId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConferenceManager.Paper'),
        ),
    ]
