# Generated by Django 3.0.5 on 2020-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0002_auto_20200511_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paperKind',
            field=models.CharField(choices=[('PDF', 'pdf'), ('DOCX', 'docx'), ('TXT', 'text')], max_length=4),
        ),
    ]
