# Generated by Django 3.0.6 on 2020-05-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0003_conferencesession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='chosenToReview',
            field=models.BooleanField(default=False),
        ),
    ]
