# Generated by Django 3.0.6 on 2020-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0003_conferencesession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='justification',
            field=models.CharField(default='-', max_length=5000),
        ),
        migrations.AddField(
            model_name='review',
            name='recommendations',
            field=models.CharField(default='-', max_length=5000),
        ),
    ]
