# Generated by Django 3.0.5 on 2020-05-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0003_auto_20200513_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='ConferenceManager.Author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ConferenceManager.Conference'),
        ),
    ]
