# Generated by Django 3.0.6 on 2020-05-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0004_auto_20200522_1657'),
        ('ConferenceManager', '0004_bid_chosentoreview'),
    ]

    operations = [
    ]
