# Generated by Django 3.0.6 on 2020-05-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceManager', '0005_merge_20200522_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='endHour',
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='roomNumber',
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='startHour',
        ),
    ]
